wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.8.10
    start_time: 1632897555
    t:
      4: 3.8.10
      5: 0.12.1
      8:
      - 2
      - 4
      - 5
path:
  desc: null
  value: genres_mod.parquet
