wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    is_jupyter_run: true
    is_kaggle_kernel: true
    python_version: 3.8.10
    session_history: code/_session_history.ipynb
    start_time: 1632916806
    t:
      3:
      - 2
      4: 3.8.10
      5: 0.12.1
      8:
      - 1
      - 2
      - 4
      - 5
